#!/usr/bin/env node
import fs from "node:fs/promises";
import {sleep,hash,fetchPage,extractJsonLdProducts,discoverProductLinks,inferAvailability,inferShipping,extractPreviousPriceFromText,historyWindows,priceTruth,dealScore,discoverDealPageLinks,classifyProductCategory,seasonalInfo,isSaudiNationalDayWindow,marketChannelFor,normalizeUrl} from "./core.mjs";
import {extractGenericProduct,mergeDefined} from "./generic-product.mjs";

const sourceParts=await Promise.all([1,2,3,4].map(async n=>JSON.parse(await fs.readFile(`data/sources/part${n}.json`,"utf8"))));
const compactRows=sourceParts.flatMap(x=>x.s||[]);
const sourcesDoc={sources:compactRows.map(r=>({key:r[0],nameAr:r[1],domain:r[2],category:[],saudiFulfillment:r[3],priority:r[4]||0,sourceRole:r[5],publishAllowed:r[6]!==false,countryScope:r[7],marketChannel:r[8],pages:(r[9]||[]).map(p=>({kind:p[0],url:p[1]})),autoDiscovery:{robots:true,sitemaps:true,navLinks:true,jsonLd:true}}))};
let history={};let scanState={rotation:0};
try{history=JSON.parse(await fs.readFile("data/history.json","utf8"))}catch{}
try{scanState=JSON.parse(await fs.readFile("data/scan-state.json","utf8"))}catch{}

const now=Date.now(),nowDate=new Date();
const maxSources=Number(process.env.RADAR_MAX_SOURCES||28),maxProductsPerSource=Number(process.env.RADAR_MAX_PRODUCTS_PER_SOURCE||7),pageDelay=Number(process.env.RADAR_PAGE_DELAY_MS||250),productDelay=Number(process.env.RADAR_PRODUCT_DELAY_MS||120),extraDealPages=Number(process.env.RADAR_EXTRA_DEAL_PAGES||3),fetchTimeout=Number(process.env.RADAR_FETCH_TIMEOUT_MS||8000);
const fetchRadar=(url,opts={})=>fetchPage(url,{...opts,timeoutMs:Number(opts.timeoutMs||fetchTimeout)});
const allDirect=(sourcesDoc.sources||[]).filter(s=>s.sourceRole!=="discovery_only"&&s.publishAllowed!==false).sort((a,b)=>(b.priority||0)-(a.priority||0));
const nationalDayActive=isSaudiNationalDayWindow(nowDate);
const seasonalSources=nationalDayActive?allDirect.filter(s=>seasonalInfo(`${s.nameAr||""} ${(s.pages||[]).map(p=>`${p.kind||""} ${p.url||""}`).join(" ")}`).active):[];
const pinnedTarget=Math.min(10,Math.max(6,Math.floor(maxSources*.24))),pinned=[],pinKeys=new Set();
for(const s of [...seasonalSources,...allDirect.filter(x=>(x.priority||0)>=98)]){if(pinKeys.has(s.key))continue;pinned.push(s);pinKeys.add(s.key);if(pinned.length>=pinnedTarget)break}
const rest=allDirect.filter(s=>!pinKeys.has(s.key)),rotatingSlots=Math.max(0,maxSources-pinned.length),start=rest.length?(Number(scanState.rotation||0)%rest.length):0,rotating=[];
for(let i=0;i<Math.min(rotatingSlots,rest.length);i++)rotating.push(rest[(start+i)%rest.length]);
const direct=[...pinned,...rotating];scanState.rotation=rest.length?(start+rotating.length)%rest.length:0;scanState.updatedAt=new Date().toISOString();scanState.lastSelected=direct.map(s=>s.key);scanState.nationalDayActive=nationalDayActive;
const sourceHealth=[],accepted=[],seenProduct=new Set();
function sourceReliability(status){if(status==="UP")return 1;if(status==="DEGRADED")return .65;return .35}
function sourceProductLimit(source){const p=Number(source.priority||0);if(p>=99)return Math.max(maxProductsPerSource,12);if(p>=95)return Math.max(maxProductsPerSource,10);return maxProductsPerSource}
async function addListingCandidates(source,pageUrl,candidates,candidateKeys,health,discoveredPages,discoveredPageKeys){const r=await fetchRadar(pageUrl);health.pagesChecked++;if(r.blocked||r.status===403||r.status===429){health.blocked++;return}if(!r.ok){health.errors++;return}health.listing2xx++;for(const p of extractJsonLdProducts(r.body,source.key,r.url)){if(!candidateKeys.has(p.productUrl)){candidateKeys.add(p.productUrl);candidates.push(p)}}for(const l of discoverProductLinks(r.body,r.url,sourceProductLimit(source))){if(!candidateKeys.has(l.url)){candidateKeys.add(l.url);candidates.push({sourceKey:source.key,sourcePageUrl:r.url,title:l.label,productUrl:l.url,imageUrl:null,currentPrice:null,currency:"SAR",availability:"unknown"})}}for(const d of discoverDealPageLinks(r.body,r.url,12)){if(!discoveredPageKeys.has(d.url)){discoveredPageKeys.add(d.url);discoveredPages.push(d.url)}}}
async function fallbackDiscoverPages(source,discoveredPages,discoveredPageKeys,health){const home=`https://${String(source.domain||"").replace(/^https?:\/\//,"").replace(/\/$/,"")}/`;if(!source.domain)return;await addListingCandidates(source,home,[],new Set(),health,discoveredPages,discoveredPageKeys);if(!source.autoDiscovery?.robots)return;const robots=await fetchRadar(new URL("/robots.txt",home).toString(),{maxBytes:250000});if(!robots.ok||robots.blocked)return;const maps=[...robots.body.matchAll(/^\s*Sitemap:\s*(https?:\/\/\S+)/gim)].map(m=>m[1]).slice(0,2);for(const sm of maps){const sr=await fetchRadar(sm,{maxBytes:500000});if(!sr.ok||sr.blocked)continue;for(const m of sr.body.matchAll(/<loc>([^<]+)<\/loc>/gi)){const u=normalizeUrl(m[1],home);if(!u)continue;const info=seasonalInfo(u);if(/sale|outlet|clearance|deal|offer|promotion|last.chance|national.day|عروض|تخفيض|تصفية/i.test(u)||info.active){if(!discoveredPageKeys.has(u)){discoveredPageKeys.add(u);discoveredPages.push(u)}if(discoveredPages.length>=extraDealPages*2)return}}}}
for(const source of direct){const channel=marketChannelFor(source),health={sourceKey:source.key,nameAr:source.nameAr,marketChannel:channel,pagesChecked:0,listing2xx:0,candidates:0,productsChecked:0,products2xx:0,accepted:0,blocked:0,errors:0,reasons:{},status:"EMPTY",checkedAt:new Date().toISOString()};const candidates=[],candidateKeys=new Set(),discoveredPages=[],discoveredPageKeys=new Set((source.pages||[]).map(p=>p.url)),limit=sourceProductLimit(source);
for(const page of source.pages||[]){await addListingCandidates(source,page.url,candidates,candidateKeys,health,discoveredPages,discoveredPageKeys);if(candidates.length>=limit)break;await sleep(pageDelay)}
for(const url of discoveredPages.slice(0,extraDealPages)){if(candidates.length>=limit)break;await addListingCandidates(source,url,candidates,candidateKeys,health,[],new Set());await sleep(pageDelay)}
if(!candidates.length&&source.autoDiscovery){const fallbacks=[],fkeys=new Set();await fallbackDiscoverPages(source,fallbacks,fkeys,health);for(const url of fallbacks.slice(0,extraDealPages)){if(candidates.length>=limit)break;await addListingCandidates(source,url,candidates,candidateKeys,health,[],new Set());await sleep(pageDelay)}}health.candidates=candidates.length;
for(const c of candidates.slice(0,limit)){if(seenProduct.has(c.productUrl))continue;seenProduct.add(c.productUrl);health.productsChecked++;const r=await fetchRadar(c.productUrl);if(r.blocked||r.status===403||r.status===429){health.reasons.blocked=(health.reasons.blocked||0)+1;continue}if(!r.ok){health.reasons.http_error=(health.reasons.http_error||0)+1;continue}health.products2xx++;const generic=extractGenericProduct(r.body,{sourceKey:source.key,pageUrl:r.url,fallbackTitle:c.title}),structured=extractJsonLdProducts(r.body,source.key,r.url)[0],p=mergeDefined(c,generic,structured);if(!p.currentPrice){health.reasons.no_price=(health.reasons.no_price||0)+1;continue}p.availability=inferAvailability(r.body,p.availability);if(p.availability!=="in_stock"){const reason=p.availability==="out_of_stock"?"out_of_stock":"availability_unknown";health.reasons[reason]=(health.reasons[reason]||0)+1;continue}p.shipping=inferShipping(source,r.body);if(!["confirmed","local_context"].includes(p.shipping)){health.reasons.shipping_unknown=(health.reasons.shipping_unknown||0)+1;continue}if(!p.previousPrice)p.previousPrice=extractPreviousPriceFromText(r.body,p.currentPrice);const key=hash(`${source.key}|${p.sku||p.productUrl||r.url}`).slice(0,32),pts=Array.isArray(history[key])?history[key]:[];pts.push({t:now,price:p.currentPrice});history[key]=pts.filter(x=>x.t>=now-120*86400000).slice(-180);const stats=historyWindows(history[key],now),truth=priceTruth(p,stats);if(!truth.verified||!(truth.percent>0)){health.reasons.no_verified_markdown=(health.reasons.no_verified_markdown||0)+1;continue}const season=seasonalInfo(p.title,c.sourcePageUrl,r.url,source.nameAr),category=classifyProductCategory(p),score=dealScore({availability:p.availability,shipping:p.shipping,discountPercent:truth.percent,evidenceType:truth.type,lowest30:stats.d30.isLowest,lowest90:stats.d90.isLowest,outlet:/outlet|clearance|last chance|final sale|تصفية|أوتلت|اوتلت/i.test(`${c.sourcePageUrl} ${source.nameAr}`),sourceReliability:sourceReliability("UP"),ageMinutes:0})+(season.active&&nationalDayActive?6:0);accepted.push({id:key,sourceKey:source.key,store:source.nameAr,marketChannel:channel,category,seasonal:season.active,seasonalCampaign:season.key,seasonalLabel:season.label,title:p.title,productUrl:p.productUrl||r.url,imageUrl:p.imageUrl||null,currentPrice:p.currentPrice,previousPrice:truth.reference,currency:p.currency||"SAR",discountPercent:truth.percent,savings:Math.round((truth.reference-p.currentPrice)*100)/100,evidenceType:truth.type,availability:p.availability,shipping:p.shipping,verifiedAt:new Date().toISOString(),lowest7d:stats.d7.isLowest,lowest30d:stats.d30.isLowest,lowest90d:stats.d90.isLowest,priceStats:stats,score:Math.min(100,Math.round(score))});health.accepted++;await sleep(productDelay)}
if(health.blocked>0&&health.listing2xx===0)health.status="BLOCKED";else if(health.accepted>0)health.status="UP";else if(health.products2xx>0||health.listing2xx>0)health.status="DEGRADED";else health.status="DOWN";sourceHealth.push(health);console.log(JSON.stringify({source:source.key,status:health.status,channel,candidates:health.candidates,accepted:health.accepted}))}
accepted.sort((a,b)=>b.score-a.score||b.discountPercent-a.discountPercent);await fs.writeFile("data/history.json",JSON.stringify(history,null,2),"utf8");await fs.writeFile("data/scan-state.json",JSON.stringify(scanState,null,2),"utf8");await fs.writeFile("public/data/deals.json",JSON.stringify({generatedAt:new Date().toISOString(),nationalDayActive,counts:{total:accepted.length,saudi:accepted.filter(x=>x.marketChannel==="saudi").length,global:accepted.filter(x=>x.marketChannel==="global").length,seasonal:accepted.filter(x=>x.seasonal).length},deals:accepted},null,2),"utf8");await fs.writeFile("public/data/source-health.json",JSON.stringify({generatedAt:new Date().toISOString(),universe:{total:compactRows.length,direct:allDirect.length,selected:direct.length,rotation:scanState.rotation,fetchTimeoutMs:fetchTimeout},sources:sourceHealth},null,2),"utf8");console.log("RADAR_SUMMARY",JSON.stringify({universe:allDirect.length,selected:sourceHealth.length,healthy:sourceHealth.filter(x=>x.status==="UP").length,degraded:sourceHealth.filter(x=>x.status==="DEGRADED").length,blocked:sourceHealth.filter(x=>x.status==="BLOCKED").length,deals:accepted.length,saudi:accepted.filter(x=>x.marketChannel==="saudi").length,global:accepted.filter(x=>x.marketChannel==="global").length,seasonal:accepted.filter(x=>x.seasonal).length,fetchTimeoutMs:fetchTimeout}));
