import assert from "node:assert/strict";
import {normalizeUrl,parseNumber,pct,windowStats,historyWindows,priceTruth,dealScore,extractJsonLdProducts,inferAvailability,discoverDealPageLinks,classifyProductCategory,seasonalInfo,isSaudiNationalDayWindow,marketChannelFor} from "./core.mjs";
assert.equal(normalizeUrl("https://x.test/p?utm_source=a&id=1#z"),"https://x.test/p?id=1");
assert.equal(parseNumber("SAR 1,299.50"),1299.50);assert.equal(pct(50,100),50);
const now=new Date("2026-08-20T00:00:00Z").getTime();const pts=[{t:new Date("2026-08-01T00:00:00Z").getTime(),price:200},{t:new Date("2026-08-10T00:00:00Z").getTime(),price:180},{t:now,price:120}];const s=windowStats(pts,30,now);assert.equal(s.min,120);assert.equal(s.max,200);assert.equal(s.isLowest,true);
const truth=priceTruth({currentPrice:50,previousPrice:100},historyWindows([],now));assert.equal(truth.verified,true);assert.equal(truth.percent,50);assert.equal(priceTruth({currentPrice:50,rrp:500},historyWindows([],now)).verified,false);
assert.equal(dealScore({availability:"out_of_stock",shipping:"confirmed",discountPercent:80,evidenceType:"store_previous_price",lowest30:true,lowest90:true,sourceReliability:1,ageMinutes:1}),0);
const html=`<script type="application/ld+json">{"@context":"https://schema.org","@type":"Product","name":"Test Shoe","url":"https://shop.test/p/1","offers":{"@type":"Offer","price":"79.99","priceCurrency":"SAR","availability":"https://schema.org/InStock"}}</script>`;const products=extractJsonLdProducts(html,"x","https://shop.test/sale");assert.equal(products.length,1);assert.equal(products[0].currentPrice,79.99);assert.equal(products[0].availability,"in_stock");assert.equal(inferAvailability("<div>Out of stock</div>","unknown"),"out_of_stock");
const nav=`<a href="/sale">Sale</a><a href="/saudi-national-day">عروض اليوم الوطني</a><a href="/about">About</a>`;assert.equal(discoverDealPageLinks(nav,"https://shop.test/").length,2);assert.equal(classifyProductCategory({title:"Al Ittihad Home Jersey"}),"ملابس");assert.equal(classifyProductCategory({title:"Eau de Parfum 100ml"}),"عطور");assert.equal(seasonalInfo("أقوى عروض اليوم الوطني").active,true);assert.equal(isSaudiNationalDayWindow(new Date("2026-08-24T00:00:00+03:00")),true);assert.equal(marketChannelFor({marketChannel:"global"}),"global");assert.equal(marketChannelFor({saudiFulfillment:"local",countryScope:"SA"}),"saudi");console.log("SELF_TEST_OK");
